var simplemaps_countrymap_mapdata={
  main_settings: {
    width: "responsive",
    background_color: "#00000000",
    background_transparent: "yes",
    border_color: "#ffffff",
    pop_ups: "detect",
    state_description: "Sin datos",
    state_color: "#D0956A",
    state_hover_color: "#F5B942",
    state_url: "",
    border_size: 1.2,
    all_states_inactive: "no",
    all_states_zoomable: "yes",
    label_color: "#ffffff",
    label_hover_color: "#ffffff",
    label_size: 11,
    label_font: "Space Grotesk",
    label_display: "auto",
    label_scale: "yes",
    hide_labels: "no",
    zoom: "yes",
    manual_zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: "-1",
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 8,
    popup_font: "13px/1.6 'Space Grotesk', sans-serif",
    popup_nocss: "no",
    div: "simplemaps-peru",
    auto_load: "yes",
    url_new_tab: "no",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "Ver detalle",
    all_locations_hidden: "yes"
  },
  state_specific: {
    PEAMA: { name:"Amazonas",      description:"Fallecidos: 1,740 | Región selva norte", color:"#E8A878", hover_color:"#F5B942", url:"default" },
    PEANC: { name:"Áncash",        description:"Fallecidos: 4,290 | Región sierra costera", color:"#C04820", hover_color:"#E07C1B", url:"default" },
    PEAPU: { name:"Apurímac",      description:"Fallecidos: 1,696 | Región sierra sur", color:"#F0C0A8", hover_color:"#F5B942", url:"default" },
    PEARE: { name:"Arequipa",      description:"Fallecidos: 10,636 | Región costa-sierra sur", color:"#E07C1B", hover_color:"#F5B942", url:"default" },
    PEAYA: { name:"Ayacucho",      description:"Fallecidos: 1,970 | Región sierra sur centro", color:"#F0A080", hover_color:"#F5B942", url:"default" },
    PECAJ: { name:"Cajamarca",     description:"Fallecidos: 2,760 | Frontera norte — dataset DS2", color:"#F5B942", hover_color:"#E07C1B", url:"default" },
    PECAL: { name:"Callao",        description:"Fallecidos: 10,853 | Puerto constitucional", color:"#5A1A06", hover_color:"#8B2E10", url:"default" },
    PECUS: { name:"Cusco",         description:"Fallecidos: 5,291 | Región sierra sur", color:"#F0A080", hover_color:"#F5B942", url:"default" },
    PEHUC: { name:"Huánuco",       description:"Fallecidos: 2,180 | Región sierra-selva central", color:"#F5B942", hover_color:"#E07C1B", url:"default" },
    PEHUV: { name:"Huancavelica",  description:"Fallecidos: — | Región altoandina", color:"#E07C1B", hover_color:"#F5B942", url:"default" },
    PEICA: { name:"Ica",           description:"Fallecidos: 3,820 | Región costa sur", color:"#F5B942", hover_color:"#E07C1B", url:"default" },
    PEJUN: { name:"Junín",         description:"Fallecidos: 7,602 | Región sierra-selva central", color:"#D05015", hover_color:"#F5B942", url:"default" },
    PELAL: { name:"La Libertad",   description:"Fallecidos: 11,005 | Región costa-sierra norte", color:"#E07C1B", hover_color:"#F5B942", url:"default" },
    PELAM: { name:"Lambayeque",    description:"Fallecidos: 4,980 | Región costa norte", color:"#EF9F27", hover_color:"#F5B942", url:"default" },
    PELIM: { name:"Lima Province", description:"Fallecidos: — | Provincia de Lima", color:"#A03818", hover_color:"#C04820", url:"default" },
    PELMA: { name:"Lima",          description:"Fallecidos: 96,461 | Mayor impacto nacional (43.6%)", color:"#8B2E10", hover_color:"#C04820", url:"default" },
    PELOR: { name:"Loreto",        description:"Fallecidos: 4,352 | Región selva amazónica", color:"#5E9420", hover_color:"#7AB430", url:"default" },
    PEMDD: { name:"Madre de Dios", description:"Fallecidos: — | Región selva sur", color:"#9FE1CB", hover_color:"#6FC4A8", url:"default" },
    PEMOQ: { name:"Moquegua",      description:"Fallecidos: — | Región costa-sierra sur", color:"#F5B942", hover_color:"#E07C1B", url:"default" },
    PEPAS: { name:"Pasco",         description:"Fallecidos: — | Región altoandina", color:"#C04820", hover_color:"#E07C1B", url:"default" },
    PEPIU: { name:"Piura",         description:"Fallecidos: 13,101 | Región norte fronteriza", color:"#F5B942", hover_color:"#E07C1B", url:"default" },
    PEPUN: { name:"Puno",          description:"Fallecidos: 3,540 | Región altoandina fronteriza", color:"#F0C0A8", hover_color:"#F5B942", url:"default" },
    PESAM: { name:"San Martín",    description:"Fallecidos: 2,910 | Región selva norcentral", color:"#EF9F27", hover_color:"#F5B942", url:"default" },
    PETAC: { name:"Tacna",         description:"Fallecidos: 1,820 | Frontera sur — dataset DS4", color:"#E07C1B", hover_color:"#F5B942", url:"default" },
    PETUM: { name:"Tumbes",        description:"Fallecidos: — | Extremo noroeste fronterizo", color:"#E8A040", hover_color:"#F5B942", url:"default" },
    PEUCA: { name:"Ucayali",       description:"Fallecidos: 2,420 | Región selva central", color:"#F0C0A8", hover_color:"#F5B942", url:"default" }
  },
  locations: {},
  labels: {
    PEAMA:{ name:"Amazonas",      parent_id:"PEAMA" },
    PEANC:{ name:"Áncash",        parent_id:"PEANC" },
    PEAPU:{ name:"Apurímac",      parent_id:"PEAPU" },
    PEARE:{ name:"Arequipa",      parent_id:"PEARE" },
    PEAYA:{ name:"Ayacucho",      parent_id:"PEAYA" },
    PECAJ:{ name:"Cajamarca",     parent_id:"PECAJ" },
    PECAL:{ name:"Callao",        parent_id:"PECAL" },
    PECUS:{ name:"Cusco",         parent_id:"PECUS" },
    PEHUC:{ name:"Huánuco",       parent_id:"PEHUC" },
    PEHUV:{ name:"Huancavelica",  parent_id:"PEHUV" },
    PEICA:{ name:"Ica",           parent_id:"PEICA" },
    PEJUN:{ name:"Junín",         parent_id:"PEJUN" },
    PELAL:{ name:"La Libertad",   parent_id:"PELAL" },
    PELAM:{ name:"Lambayeque",    parent_id:"PELAM" },
    PELIM:{ name:"Lima Prov.",    parent_id:"PELIM" },
    PELMA:{ name:"Lima",          parent_id:"PELMA" },
    PELOR:{ name:"Loreto",        parent_id:"PELOR" },
    PEMDD:{ name:"Madre de Dios", parent_id:"PEMDD" },
    PEMOQ:{ name:"Moquegua",      parent_id:"PEMOQ" },
    PEPAS:{ name:"Pasco",         parent_id:"PEPAS" },
    PEPIU:{ name:"Piura",         parent_id:"PEPIU" },
    PEPUN:{ name:"Puno",          parent_id:"PEPUN" },
    PESAM:{ name:"San Martín",    parent_id:"PESAM" },
    PETAC:{ name:"Tacna",         parent_id:"PETAC" },
    PETUM:{ name:"Tumbes",        parent_id:"PETUM" },
    PEUCA:{ name:"Ucayali",       parent_id:"PEUCA" }
  }
};